#!/bin/sh

# 注意权限问题
repo_path="/home/git/sample-test"
cd $repo_path
unset GIT_DIR
git config --global core.quotepath false
git pull 1>/tmp/sample-git.out 2>&1
php -f /home/vagrant/Code/Swagger-Notify/run.php $repo_path 1>/tmp/swagger-notify.out 2>&1